### ISSUE TITLE
GridSettings are not shown

### ISSUE THREAD

**Issue by johannessteu** [johannessteu/JohannesSteu.Bootstrap.GridSystem#3]
After an Neos Update the second tab with grid settings are no longer shown.

To Hotfix this use

```
'JohannesSteu.Bootstrap.GridSystem:Row':
  ui:
    inspector:
      groups:
        gridsystem:
          tab: ~
```

This will move all settings in the first tab
